#!/bin/bash
set -e
echo "========================================================"
echo "Running synth..."

yosys \
   -p "read -sv x_fpga.sv" \
   -p "read -sv x_fpga_cells.sv" \
   -p "read -sv ../rtl/tt_um_ashleyjr_delay_line.sv" \
   -p "read -sv ../rtl/x_uart_rx.sv" \
   -p "read -sv ../rtl/x_uart_tx.sv" \
   -p "read -sv ../rtl/x_driver.sv" \
   -p "read -sv ../rtl/x_delay_line.sv" \
   -p "read -sv ../rtl/x_delay_line_cell.sv" \
   -p "read -sv ../rtl/x_delay_line_bulk.sv" \
   -p "synth_ice40 -top x_fpga -json x_fpga.json"
echo "========================================================"
echo "Running place and route..."
rm -f pnr.log
nextpnr-ice40 --hx8k --json x_fpga.json --package ct256 --pcf x_fpga.pcf --asc x_fpga.asc
echo "========================================================"
echo "Running Timing check..."
icetime -d hx8k x_fpga.asc > x_fpga.time
cat x_fpga.time
echo "========================================================"
echo "Packing..."
icepack x_fpga.asc x_fpga.bin
echo "========================================================"
echo "Writing..."
iceprog  -S x_fpga.bin
echo "========================================================"
